# Generated by Django 3.1.1 on 2020-10-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201027_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='lname',
        ),
    ]
