# Generated by Django 3.1.1 on 2020-10-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201027_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
