# Generated by Django 3.1.1 on 2020-10-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='harsh@xyz.com', max_length=70),
        ),
    ]
