# Generated by Django 3.1.1 on 2020-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='image',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
